version: 2
jobs:
  build:
    machine: true
    working_directory: ~/repo

    environment:
      - ENV: "dev"
      - AWS_ACCOUNT: "500651484941"
      - AWS_DEFAULT_REGION: "us-east-1"
      - NAME_PREFIX: "dev-botchain-"

    steps:
      - checkout

      - run: echo 'export MOUNTS="-v $PWD:/app"' >> $BASH_ENV
      - run: echo 'export DOCKER_OPTS="-e AWS_ACCESS_KEY_ID -e AWS_SECRET_ACCESS_KEY -e AWS_DEFAULT_REGION $MOUNTS"' >> $BASH_ENV

      # run tests!
      # - run: ?

      # Deploy to s3
      - run:
          name: deploy
          command: |
            if [[ $CIRCLE_BRANCH == "master" ]]; then
              docker run $DOCKER_OPTS simplygenius/aws-ecs-deploy aws-assume-role \
                  $AWS_ACCOUNT \
                  $ENV-deployer \
                  aws cp --acl bucket-owner-full-control --recursive \
                    --exclude "*" --include public --include src
                    /app/ s3://talla-botchain-dev-ui/
            fi
